-- Rename ReputationEvent enum values from mixed case to UPPER_SNAKE_CASE
ALTER TYPE ""ReputationEvent"" RENAME VALUE ""RESOURCE_UPVOTED_received"" TO ""RESOURCE_UPVOTED_RECEIVED"";
ALTER TYPE ""ReputationEvent"" RENAME VALUE ""DISCUSSION_UPVOTED_received"" TO ""DISCUSSION_UPVOTED_RECEIVED"";
ALTER TYPE ""ReputationEvent"" RENAME VALUE ""QUESTION_UPVOTED_received"" TO ""QUESTION_UPVOTED_RECEIVED"";
ALTER TYPE ""ReputationEvent"" RENAME VALUE ""ANSWER_UPVOTED_received"" TO ""ANSWER_UPVOTED_RECEIVED"";
ALTER TYPE ""ReputationEvent"" RENAME VALUE ""RESOURCE_DOWNVOTED_received"" TO ""RESOURCE_DOWNVOTED_RECEIVED"";
ALTER TYPE ""ReputationEvent"" RENAME VALUE ""RESOURCE_DOWNVOTED_given"" TO ""RESOURCE_DOWNVOTED_GIVEN"";
ALTER TYPE ""ReputationEvent"" RENAME VALUE ""DISCUSSION_DOWNVOTED_received"" TO ""DISCUSSION_DOWNVOTED_RECEIVED"";
ALTER TYPE ""ReputationEvent"" RENAME VALUE ""QUESTION_DOWNVOTED_received"" TO ""QUESTION_DOWNVOTED_RECEIVED"";
ALTER TYPE ""ReputationEvent"" RENAME VALUE ""ANSWER_DOWNVOTED_received"" TO ""ANSWER_DOWNVOTED_RECEIVED"";
