import { prisma } from "../../src/app/lib/prisma";
import { Department } from "../../src/generated/prisma/enums";
interface ICourse {
  code: string;
  name: string;
  department: Department;
  semester: number;
}

const CSE: ICourse[] = [
  {
    code: "CSE-1211",
    name: "Discrete Mathematics",
    department: Department.CSE,
    semester: 1,
  },
  {
    code: "ENG-1101",
    name: "English I",
    department: Department.CSE,
    semester: 1,
  },
  {
    code: "PHY-1201",
    name: "Physics I (Heat and Thermodynamics, Properties of Matters, Waves and Oscillations)",
    department: Department.CSE,
    semester: 1,
  },
  {
    code: "CSE-1111",
    name: "Introduction to Computers",
    department: Department.CSE,
    semester: 1,
  },
  {
    code: "EEE-1111",
    name: "Electrical Engineering and Circuit Analysis",
    department: Department.CSE,
    semester: 2,
  },
  {
    code: "EEE-1121",
    name: "Electrical Engineering and Circuit Analysis Lab Work",
    department: Department.CSE,
    semester: 2,
  },
  {
    code: "CSE-1112",
    name: "Structured Programming Language",
    department: Department.CSE,
    semester: 2,
  },
  {
    code: "CSE-1121",
    name: "Structured Programming Language Lab Works",
    department: Department.CSE,
    semester: 2,
  },
  {
    code: "MATH-1101",
    name: "Mathematics I (Differential Calculus and Integral Calculus)",
    department: Department.CSE,
    semester: 2,
  },
  {
    code: "MATH-2103",
    name: "Mathematics III (Matrices, Vectors & Coordinate Geometry)",
    department: Department.CSE,
    semester: 3,
  },
  {
    code: "CSE-2263",
    name: "Algorithms Design & Analysis",
    department: Department.CSE,
    semester: 3,
  },
  {
    code: "CSE-2264",
    name: "Algorithms Design & Analysis Lab Work",
    department: Department.CSE,
    semester: 3,
  },
  {
    code: "CSE-2215",
    name: "Digital logic Design",
    department: Department.CSE,
    semester: 3,
  },
  {
    code: "CSE-2265",
    name: "Digital Logic Design Lab Work",
    department: Department.CSE,
    semester: 3,
  },
  {
    code: "CSE-2319",
    name: "Database Management System",
    department: Department.CSE,
    semester: 3,
  },
  {
    code: "CSE-2367",
    name: "Database Management Systems Lab Work",
    department: Department.CSE,
    semester: 3,
  },
  {
    code: "MATH-2204",
    name: "Mathematics IV (Complex Variable & Laplace Transformation)",
    department: Department.CSE,
    semester: 4,
  },
  {
    code: "CSE-2109",
    name: "Electronic Engineering",
    department: Department.CSE,
    semester: 4,
  },
  {
    code: "CSE-2161",
    name: "Electronic Engineering Lab Work",
    department: Department.CSE,
    semester: 4,
  },
  {
    code: "CSE-3168",
    name: "Numerical Methods",
    department: Department.CSE,
    semester: 4,
  },
  {
    code: "CSE-3186",
    name: "Numerical Methods Lab work",
    department: Department.CSE,
    semester: 4,
  },
  {
    code: "CSE-3124",
    name: "Microprocessor and Assembly Language",
    department: Department.CSE,
    semester: 4,
  },
  {
    code: "CSE-3171",
    name: "Microprocessor and Assembly Language programming Lab Work",
    department: Department.CSE,
    semester: 4,
  },
  {
    code: "CSE-2291",
    name: "Software Development II (Database Programming)",
    department: Department.CSE,
    semester: 4,
  },
  {
    code: "MATH-2305",
    name: "Mathematics V (Statistics and Probability)",
    department: Department.CSE,
    semester: 5,
  },
  {
    code: "CSE-2317",
    name: "Digital Electronics & Pulse Technique",
    department: Department.CSE,
    semester: 5,
  },
  {
    code: "CSE-2366",
    name: "Digital Electronics & Pulse Technique Lab Work",
    department: Department.CSE,
    semester: 5,
  },
  {
    code: "CSE-3169",
    name: "Theory of Computation",
    department: Department.CSE,
    semester: 5,
  },
  {
    code: "CSE-3170",
    name: "Computer Architecture",
    department: Department.CSE,
    semester: 5,
  },
  {
    code: "CSE-3227",
    name: "Data Communication",
    department: Department.CSE,
    semester: 5,
  },
  {
    code: "CSE-3228",
    name: "Compiler Design",
    department: Department.CSE,
    semester: 6,
  },
  {
    code: "CSE-3272",
    name: "Compiler Design Lab Work",
    department: Department.CSE,
    semester: 6,
  },
  {
    code: "CSE-3331",
    name: "Operating System",
    department: Department.CSE,
    semester: 6,
  },
  {
    code: "CSE-3373",
    name: "Operating System Lab Work",
    department: Department.CSE,
    semester: 6,
  },
  {
    code: "CSE-3333",
    name: "Object-Oriented Programming II (Java)",
    department: Department.CSE,
    semester: 6,
  },
  {
    code: "CSE-3374",
    name: "Object-Oriented Programming II Lab Work",
    department: Department.CSE,
    semester: 6,
  },
  {
    code: "CSE-3226",
    name: "Mathematical Analysis for Computer Science",
    department: Department.CSE,
    semester: 6,
  },
  {
    code: "CSE-3230",
    name: "Software Engineering",
    department: Department.CSE,
    semester: 7,
  },
  {
    code: "CSE-4136",
    name: "Computer Networks",
    department: Department.CSE,
    semester: 7,
  },
  {
    code: "CSE-4176",
    name: "Computer Networks Lab Work",
    department: Department.CSE,
    semester: 7,
  },
  {
    code: "CSE-4138",
    name: "Computer Peripherals and Interfacing",
    department: Department.CSE,
    semester: 7,
  },
  {
    code: "CSE-4177",
    name: "Computer Peripherals and Interfacing Lab",
    department: Department.CSE,
    semester: 7,
  },
  {
    code: "CSE-4349",
    name: "Management Information Systems",
    department: Department.CSE,
    semester: 7,
  },
  {
    code: "CSE-4389",
    name: "Field Work (Industrial Training)",
    department: Department.CSE,
    semester: 7,
  },
  {
    code: "CSE-4278",
    name: "Computer Graphics and Multimedia System Design",
    department: Department.CSE,
    semester: 8,
  },
  {
    code: "CSE-4288",
    name: "Computer Graphics Lab Work",
    department: Department.CSE,
    semester: 8,
  },
  {
    code: "CSE-4241",
    name: "VLSI Design",
    department: Department.CSE,
    semester: 8,
  },
  {
    code: "CSE-4279",
    name: "VLSI Design Lab Work",
    department: Department.CSE,
    semester: 8,
  },
  {
    code: "CSE-3375",
    name: "Communication Engineering",
    department: Department.CSE,
    semester: 8,
  },
  {
    code: "CSE-3292",
    name: "Software Development III (Web Programming)",
    department: Department.CSE,
    semester: 8,
  },
  {
    code: "IPE-4101",
    name: "Industrial Management",
    department: Department.CSE,
    semester: 8,
  },
  {
    code: "CSE-4000",
    name: "Project & Thesis",
    department: Department.CSE,
    semester: 8,
  },
  {
    code: "CSE-4355",
    name: "Artificial intelligence & Expert Systems",
    department: Department.CSE,
    semester: 9,
  },
  {
    code: "CSE-4385",
    name: "Artificial intelligence & Expert Systems Lab Work",
    department: Department.CSE,
    semester: 9,
  },
  {
    code: "CSE-4351",
    name: "Image Processing & Computer Vision",
    department: Department.CSE,
    semester: 9,
  },
  {
    code: "CSE-4383",
    name: "Image Processing & Computer Vision Lab Work",
    department: Department.CSE,
    semester: 9,
  },
  {
    code: "ENG-1100",
    name: "English Foundation",
    department: Department.CSE,
    semester: 1,
  },
  {
    code: "HUM-1301",
    name: "Humanities & Social Sciences",
    department: Department.CSE,
    semester: 1,
  },
  {
    code: "GED-1202",
    name: "General Education Course",
    department: Department.CSE,
    semester: 1,
  },
  {
    code: "CHE-2103",
    name: "Chemistry",
    department: Department.CSE,
    semester: 3,
  },
];

const EEE: ICourse[] = [
  {
    code: "MATH-1101",
    name: "Mathematics I",
    department: Department.EEE,
    semester: 1,
  },
  {
    code: "EEE-1101",
    name: "Electrical Circuits I",
    department: Department.EEE,
    semester: 1,
  },
  {
    code: "ENG-1101",
    name: "English Reading, Writing and Speaking",
    department: Department.EEE,
    semester: 1,
  },
  {
    code: "PHY-1101",
    name: "Physics I",
    department: Department.EEE,
    semester: 1,
  },
  {
    code: "ENG-1203",
    name: "English II (Advanced)",
    department: Department.EEE,
    semester: 2,
  },
  {
    code: "CHM-1201",
    name: "Chemistry",
    department: Department.EEE,
    semester: 2,
  },
  {
    code: "CHM-1202",
    name: "Chemistry LAB",
    department: Department.EEE,
    semester: 2,
  },
  {
    code: "PHY-1203",
    name: "Physics II",
    department: Department.EEE,
    semester: 2,
  },
  {
    code: "PHY-1204",
    name: "Physics Lab",
    department: Department.EEE,
    semester: 2,
  },
  {
    code: "EEE-1203",
    name: "Electrical Circuits II",
    department: Department.EEE,
    semester: 2,
  },
  {
    code: "EEE-1102",
    name: "Electrical Circuits Lab",
    department: Department.EEE,
    semester: 2,
  },
  {
    code: "GED-1301",
    name: "Socioeconomic Study of Bangladesh / Introduction to Public Administration / Government and Politics",
    department: Department.EEE,
    semester: 3,
  },
  {
    code: "EEE-1305",
    name: "Electronic Devices",
    department: Department.EEE,
    semester: 3,
  },
  {
    code: "EEE-1306",
    name: "Electronic Devices LAB",
    department: Department.EEE,
    semester: 3,
  },
  {
    code: "ME-1301",
    name: "Mechanical Engineering Fundamentals",
    department: Department.EEE,
    semester: 3,
  },
  {
    code: "EEE-2109",
    name: "Analog Electronics II",
    department: Department.EEE,
    semester: 4,
  },
  {
    code: "EEE-2216",
    name: "Analog Electronics Lab",
    department: Department.EEE,
    semester: 4,
  },
  {
    code: "EEE-2108",
    name: "Structured Programming Language Lab",
    department: Department.EEE,
    semester: 4,
  },
  {
    code: "EEE-2111",
    name: "Numerical Methods",
    department: Department.EEE,
    semester: 4,
  },
  {
    code: "EEE-2112",
    name: "Numerical Methods Lab",
    department: Department.EEE,
    semester: 4,
  },
  {
    code: "EEE-2114",
    name: "Engineering Drawing",
    department: Department.EEE,
    semester: 4,
  },
  {
    code: "EEE-2219",
    name: "Electromagnetic Fields & Waves",
    department: Department.EEE,
    semester: 4,
  },
  {
    code: "EEE-2217",
    name: "Digital Electronics",
    department: Department.EEE,
    semester: 5,
  },
  {
    code: "EEE-2218",
    name: "Digital Electronics Lab",
    department: Department.EEE,
    semester: 5,
  },
  {
    code: "EEE-3234",
    name: "Energy Conversion Lab",
    department: Department.EEE,
    semester: 5,
  },
  {
    code: "EEE-2323",
    name: "Energy Conversion I",
    department: Department.EEE,
    semester: 5,
  },
  {
    code: "EEE-2321",
    name: "Signals & Systems",
    department: Department.EEE,
    semester: 5,
  },
  {
    code: "MATH-3109",
    name: "Mathematics V (Statistics and Probability)",
    department: Department.EEE,
    semester: 5,
  },
  {
    code: "EEE-3340",
    name: "Electrical Services Design",
    department: Department.EEE,
    semester: 6,
  },
  {
    code: "EEE-3127",
    name: "Digital Signal Processing",
    department: Department.EEE,
    semester: 6,
  },
  {
    code: "EEE-3128",
    name: "Digital Signal Processing Lab",
    department: Department.EEE,
    semester: 6,
  },
  {
    code: "EEE-3335",
    name: "Communication Theory",
    department: Department.EEE,
    semester: 6,
  },
  {
    code: "EEE-3336",
    name: "Communication LAB",
    department: Department.EEE,
    semester: 6,
  },
  {
    code: "EEE-4273",
    name: "Power Electronic",
    department: Department.EEE,
    semester: 7,
  },
  {
    code: "EEE-4274",
    name: "Power Electronic Lab",
    department: Department.EEE,
    semester: 7,
  },
  {
    code: "EEE-3129",
    name: "Microprocessor and Assembly Language",
    department: Department.EEE,
    semester: 7,
  },
  {
    code: "EEE-3338",
    name: "Control Systems Engineering Lab",
    department: Department.EEE,
    semester: 7,
  },
  {
    code: "EEE-3337",
    name: "Control Systems Engineering",
    department: Department.EEE,
    semester: 7,
  },
  {
    code: "EEE-3130",
    name: "Microprocessor and Assembly Language Lab",
    department: Department.EEE,
    semester: 7,
  },
  {
    code: "EEE-3231",
    name: "Power System I",
    department: Department.EEE,
    semester: 8,
  },
  {
    code: "EEE-3232",
    name: "Power System I Laboratory",
    department: Department.EEE,
    semester: 8,
  },
  {
    code: "EEE-4277",
    name: "Power System Protection",
    department: Department.EEE,
    semester: 8,
  },
  {
    code: "EEE-4278",
    name: "Power System Protection Laboratory",
    department: Department.EEE,
    semester: 8,
  },
  {
    code: "IPE-4101",
    name: "Industrial Management",
    department: Department.EEE,
    semester: 8,
  },
  {
    code: "EEE-4142",
    name: "Industrial Training",
    department: Department.EEE,
    semester: 8,
  },
  {
    code: "EEE-4389",
    name: "Renewable Energy Technology",
    department: Department.EEE,
    semester: 9,
  },
  {
    code: "EEE-4293",
    name: "Microprocessor System Design",
    department: Department.EEE,
    semester: 9,
  },
  {
    code: "EEE-4294",
    name: "Microprocessor System Design Laboratory",
    department: Department.EEE,
    semester: 9,
  },
  {
    code: "EEE-4161",
    name: "Power System II",
    department: Department.EEE,
    semester: 9,
  },
  {
    code: "EEE-4143",
    name: "Solid State Devices",
    department: Department.EEE,
    semester: 9,
  },
  {
    code: "EEE-2325",
    name: "Electrical Properties of Materials",
    department: Department.EEE,
    semester: 9,
  },
  {
    code: "EEE-4131",
    name: "Digital Signal Processing II",
    department: Department.EEE,
    semester: 10,
  },
  {
    code: "EEE-4253",
    name: "VLSI I",
    department: Department.EEE,
    semester: 10,
  },
  {
    code: "EEE-4254",
    name: "VLSI I Laboratory",
    department: Department.EEE,
    semester: 10,
  },
  {
    code: "HUM-3303",
    name: "Economics",
    department: Department.EEE,
    semester: 10,
  },
  {
    code: "EEE-4275",
    name: "Power Plant Engineering",
    department: Department.EEE,
    semester: 10,
  },
  {
    code: "EEE-4000",
    name: "Project",
    department: Department.EEE,
    semester: 10,
  },
  {
    code: "EEE-4328",
    name: "Measurement and Instrumentation Laboratory",
    department: Department.EEE,
    semester: 11,
  },
  {
    code: "HUM-3101",
    name: "Financial and Managerial Accounting",
    department: Department.EEE,
    semester: 11,
  },
  {
    code: "EEE-4258",
    name: "VLSI II Laboratory",
    department: Department.EEE,
    semester: 12,
  },
];

const ME: ICourse[] = [
  {
    code: "ME-1101",
    name: "Engineering Materials",
    department: Department.ME,
    semester: 1,
  },
  {
    code: "ME-1100",
    name: "Engineering Drawing",
    department: Department.ME,
    semester: 1,
  },
  {
    code: "CHE-1101",
    name: "Chemistry",
    department: Department.ME,
    semester: 1,
  },
  {
    code: "CHE-1102",
    name: "Chemistry Lab",
    department: Department.ME,
    semester: 1,
  },
  {
    code: "ENG-1101",
    name: "English",
    department: Department.ME,
    semester: 1,
  },
  {
    code: "MATH-1101",
    name: "Engineering Mathematics-I",
    department: Department.ME,
    semester: 1,
  },
  {
    code: "PHY-1101",
    name: "Physics",
    department: Department.ME,
    semester: 1,
  },
  {
    code: "PHY-1104",
    name: "Physics Lab",
    department: Department.ME,
    semester: 1,
  },
  {
    code: "BAN-1101",
    name: "Bangladesh Studies",
    department: Department.ME,
    semester: 1,
  },
  {
    code: "ME-1201",
    name: "Manufacturing Engineering",
    department: Department.ME,
    semester: 2,
  },
  {
    code: "ME-1204",
    name: "Engineering Workshop",
    department: Department.ME,
    semester: 2,
  },
  {
    code: "ME-1202",
    name: "Engineering Static",
    department: Department.ME,
    semester: 2,
  },
  {
    code: "PHY-1201",
    name: "Modern Physics",
    department: Department.ME,
    semester: 2,
  },
  {
    code: "BAN-1201",
    name: "Bengali Language and Literature",
    department: Department.ME,
    semester: 2,
  },
  {
    code: "MATH-1201",
    name: "Engineering Mathematics - II",
    department: Department.ME,
    semester: 2,
  },
  {
    code: "EE-1201",
    name: "Fundamental Electrical Engineering",
    department: Department.ME,
    semester: 2,
  },
  {
    code: "EE-2102",
    name: "Fundamental Electrical Engineering Lab",
    department: Department.ME,
    semester: 2,
  },
  {
    code: "ME-2301",
    name: "Engineering Dynamics",
    department: Department.ME,
    semester: 3,
  },
  {
    code: "MATH-2301",
    name: "Engineering Mathematics III",
    department: Department.ME,
    semester: 3,
  },
  {
    code: "ME-2303",
    name: "Fluid Mechanics -I",
    department: Department.ME,
    semester: 3,
  },
  {
    code: "ECON-2301",
    name: "Engineering Economics",
    department: Department.ME,
    semester: 3,
  },
  {
    code: "CSE-2301",
    name: "Computer Programming Language",
    department: Department.ME,
    semester: 3,
  },
  {
    code: "ACC-2301",
    name: "Engineering Accounting",
    department: Department.ME,
    semester: 3,
  },
  {
    code: "ME-2304",
    name: "Fluid Mechanics -I Lab",
    department: Department.ME,
    semester: 3,
  },
  {
    code: "ME-2306",
    name: "Engineering Mechanics Lab",
    department: Department.ME,
    semester: 3,
  },
  {
    code: "MATH-2401",
    name: "Engineering Mathematics IV",
    department: Department.ME,
    semester: 4,
  },
  {
    code: "ME-2401",
    name: "Fluid Mechanics II",
    department: Department.ME,
    semester: 4,
  },
  {
    code: "ME-2403",
    name: "Strength of Materials",
    department: Department.ME,
    semester: 4,
  },
  {
    code: "BUS-2401",
    name: "Business Communication",
    department: Department.ME,
    semester: 4,
  },
  {
    code: "ME-2405",
    name: "Mechanics of Machine",
    department: Department.ME,
    semester: 4,
  },
  {
    code: "ME-2407",
    name: "Engineering Thermodynamics",
    department: Department.ME,
    semester: 4,
  },
  {
    code: "ME-2402",
    name: "Fluid Mechanics II Lab",
    department: Department.ME,
    semester: 4,
  },
  {
    code: "ME-2406",
    name: "Mechanics of Machine Lab",
    department: Department.ME,
    semester: 4,
  },
  {
    code: "ME-2408",
    name: "Engineering Thermodynamics Lab",
    department: Department.ME,
    semester: 4,
  },
  {
    code: "ME-3501",
    name: "Heat and Mass Transfer",
    department: Department.ME,
    semester: 5,
  },
  {
    code: "ME-3503",
    name: "Internal Combustion Engine",
    department: Department.ME,
    semester: 5,
  },
  {
    code: "EE-3501",
    name: "Electrical Circuit",
    department: Department.ME,
    semester: 5,
  },
  {
    code: "ME-3505",
    name: "Refrigeration and Air-conditioning",
    department: Department.ME,
    semester: 5,
  },
  {
    code: "ME-3507",
    name: "Machine Design I",
    department: Department.ME,
    semester: 5,
  },
  {
    code: "ME-3509",
    name: "Measurement and Instrumentation",
    department: Department.ME,
    semester: 5,
  },
  {
    code: "ME-3502",
    name: "Heat and Mass Transfer Lab",
    department: Department.ME,
    semester: 5,
  },
  {
    code: "EE-3502",
    name: "Electric Circuit Lab",
    department: Department.ME,
    semester: 5,
  },
  {
    code: "ME-3506",
    name: "Measurement and Instrumentation Lab",
    department: Department.ME,
    semester: 5,
  },
  {
    code: "ME-3600",
    name: "Machine Design II",
    department: Department.ME,
    semester: 6,
  },
  {
    code: "HRM-3601",
    name: "Ethics and Law for Engineering",
    department: Department.ME,
    semester: 6,
  },
  {
    code: "ME-3601",
    name: "Machine Tools Engineering",
    department: Department.ME,
    semester: 6,
  },
  {
    code: "ME-3603",
    name: "Computer Aided Engineering",
    department: Department.ME,
    semester: 6,
  },
  {
    code: "ME-3605",
    name: "Mechatronics and Modern Control",
    department: Department.ME,
    semester: 6,
  },
  {
    code: "ME-3607",
    name: "Elective I",
    department: Department.ME,
    semester: 6,
  },
  {
    code: "ME-3604",
    name: "Computer Aided Engineering Lab",
    department: Department.ME,
    semester: 6,
  },
  {
    code: "ME-3609",
    name: "Engineering Statistics",
    department: Department.ME,
    semester: 6,
  },
];

const courses: ICourse[] = [...CSE, ...EEE,...ME];

export async function seedAcademic() {
  const result = await prisma.course.createMany({
    data: courses,
    skipDuplicates: true,
  });

  console.log(`Seeded ${result.count} courses.`);
}