import status from "http-status";
import AppError from "../../errorHelpers/AppError";
import { prisma } from "../../lib/prisma";
import { auth } from "../../lib/auth";
import { auditService, AUDIT_ACTIONS } from "./audit.service";

/** 30 days in milliseconds for deletion grace period */
const DELETION_GRACE_PERIOD_MS = 30 * 24 * 60 * 60 * 1000;

/** Export file expiry: 7 days */
const EXPORT_EXPIRY_MS = 7 * 24 * 60 * 60 * 1000;

/**
 * Verify user password via Better Auth sign-in.
 * Throws if password is incorrect.
 */
const verifyPassword = async (userId: string, password: string) => {
  const user = await prisma.user.findUnique({
    where: { id: userId },
    select: { email: true },
  });

  if (!user) {
    throw new AppError(status.NOT_FOUND, "User not found.");
  }

  try {
    const result = await auth.api.signInEmail({
      body: { email: user.email, password },
    });

    // Delete the session that was just created during verification
    if (result?.token) {
      const session = await prisma.session.findFirst({
        where: { token: result.token },
      });
      if (session) {
        await prisma.session.delete({ where: { id: session.id } });
      }
    }

    return true;
  } catch {
    throw new AppError(status.BAD_REQUEST, "Invalid password.");
  }
};

/**
 * Request a data export job.
 * Creates an ExportJob and triggers background processing.
 */
const requestExport = async (userId: string, type: string) => {
  // Create the export job
  const job = await prisma.exportJob.create({
    data: {
      userId,
      type,
      status: "PROCESSING",
      expiresAt: new Date(Date.now() + EXPORT_EXPIRY_MS),
    },
  });

  // Log the export request
  await auditService.logAction({
    userId,
    action: AUDIT_ACTIONS.DATA_EXPORTED,
    entityType: "EXPORT_JOB",
    entityId: job.id,
    details: { type },
  });

  // In production, this would trigger a background job/queue.
  // For now, we simulate immediate completion for small exports.
  // The file URL would be generated by a background worker.
  // We leave the job in PROCESSING status — the client can poll for completion.

  return {
    jobId: job.id,
    status: job.status,
    message: "Export request submitted. You will be notified when it is ready.",
  };
};

/**
 * Get export job status.
 */
const getExportStatus = async (userId: string, jobId: string) => {
  const job = await prisma.exportJob.findUnique({
    where: { id: jobId },
  });

  if (!job) {
    throw new AppError(status.NOT_FOUND, "Export job not found.");
  }

  if (job.userId !== userId) {
    throw new AppError(status.FORBIDDEN, "Access denied.");
  }

  return {
    jobId: job.id,
    type: job.type,
    status: job.status,
    fileUrl: job.fileUrl,
    expiresAt: job.expiresAt,
    createdAt: job.createdAt,
  };
};

/**
 * Get a signed download URL for a completed export.
 */
const downloadExport = async (userId: string, jobId: string) => {
  const job = await prisma.exportJob.findUnique({
    where: { id: jobId },
  });

  if (!job) {
    throw new AppError(status.NOT_FOUND, "Export job not found.");
  }

  if (job.userId !== userId) {
    throw new AppError(status.FORBIDDEN, "Access denied.");
  }

  if (job.status !== "COMPLETED") {
    throw new AppError(
      status.BAD_REQUEST,
      "Export is not ready for download yet.",
    );
  }

  if (job.expiresAt && job.expiresAt < new Date()) {
    throw new AppError(status.GONE, "Export file has expired.");
  }

  return {
    downloadUrl: job.fileUrl,
    expiresAt: job.expiresAt,
  };
};

/**
 * Request a full account archive.
 * Verifies password and creates an archive job.
 */
const requestArchive = async (userId: string, password: string) => {
  await verifyPassword(userId, password);

  const job = await prisma.exportJob.create({
    data: {
      userId,
      type: "ARCHIVE",
      status: "PROCESSING",
      expiresAt: new Date(Date.now() + EXPORT_EXPIRY_MS),
    },
  });

  await auditService.logAction({
    userId,
    action: AUDIT_ACTIONS.ARCHIVE_REQUESTED,
    entityType: "EXPORT_JOB",
    entityId: job.id,
  });

  return {
    jobId: job.id,
    status: job.status,
    message:
      "Archive request submitted. You will be notified when it is ready.",
  };
};

/**
 * Deactivate user account.
 * Verifies password, marks user as deactivated, invalidates all sessions.
 */
const deactivateAccount = async (
  userId: string,
  password: string,
  ipAddress?: string,
) => {
  await verifyPassword(userId, password);

  // Mark user as deactivated
  await prisma.user.update({
    where: { id: userId },
    data: {
      isDeactivated: true,
      deactivationRequestedAt: new Date(),
    },
  });

  // Invalidate all sessions except current
  const deletedSessions = await prisma.session.deleteMany({
    where: { userId },
  });

  // Log the deactivation
  await auditService.logAction({
    userId,
    action: AUDIT_ACTIONS.ACCOUNT_DEACTIVATED,
    entityType: "USER",
    entityId: userId,
    details: { sessionsInvalidated: deletedSessions.count },
    ipAddress,
  });

  return {
    message: "Account deactivated successfully. All sessions have been invalidated.",
    sessionsInvalidated: deletedSessions.count,
  };
};

/**
 * Reactivate a deactivated account.
 * Verifies password and restores user to active status.
 */
const reactivateAccount = async (
  userId: string,
  password: string,
  ipAddress?: string,
) => {
  const user = await prisma.user.findUnique({
    where: { id: userId },
    select: { isDeactivated: true },
  });

  if (!user) {
    throw new AppError(status.NOT_FOUND, "User not found.");
  }

  if (!user.isDeactivated) {
    throw new AppError(status.BAD_REQUEST, "Account is not deactivated.");
  }

  await verifyPassword(userId, password);

  await prisma.user.update({
    where: { id: userId },
    data: {
      isDeactivated: false,
      deactivationRequestedAt: null,
    },
  });

  await auditService.logAction({
    userId,
    action: AUDIT_ACTIONS.ACCOUNT_REACTIVATED,
    entityType: "USER",
    entityId: userId,
    ipAddress,
  });

  return { message: "Account reactivated successfully." };
};

/**
 * Request account deletion with 30-day grace period.
 * Verifies password and schedules deletion.
 */
const requestDeletion = async (
  userId: string,
  password: string,
  reason?: string,
  ipAddress?: string,
) => {
  await verifyPassword(userId, password);

  const scheduledDeletionAt = new Date(
    Date.now() + DELETION_GRACE_PERIOD_MS,
  );

  await prisma.user.update({
    where: { id: userId },
    data: { scheduledDeletionAt },
  });

  await auditService.logAction({
    userId,
    action: AUDIT_ACTIONS.ACCOUNT_DELETION_REQUESTED,
    entityType: "USER",
    entityId: userId,
    details: {
      scheduledDeletionAt: scheduledDeletionAt.toISOString(),
      reason: reason ?? null,
    },
    ipAddress,
  });

  return {
    message: `Account will be permanently deleted on ${scheduledDeletionAt.toLocaleDateString()}. You can cancel this request within 30 days.`,
    scheduledDeletionAt,
  };
};

/**
 * Cancel a scheduled account deletion.
 */
const cancelDeletion = async (userId: string, ipAddress?: string) => {
  const user = await prisma.user.findUnique({
    where: { id: userId },
    select: { scheduledDeletionAt: true },
  });

  if (!user) {
    throw new AppError(status.NOT_FOUND, "User not found.");
  }

  if (!user.scheduledDeletionAt) {
    throw new AppError(
      status.BAD_REQUEST,
      "No deletion is currently scheduled.",
    );
  }

  await prisma.user.update({
    where: { id: userId },
    data: { scheduledDeletionAt: null },
  });

  await auditService.logAction({
    userId,
    action: AUDIT_ACTIONS.ACCOUNT_DELETION_CANCELLED,
    entityType: "USER",
    entityId: userId,
    ipAddress,
  });

  return { message: "Account deletion has been cancelled." };
};

/**
 * Execute scheduled deletion (called by scheduler after 30 days).
 * Permanently deletes user data and marks account as deleted.
 */
const executeDeletion = async (userId: string) => {
  const user = await prisma.user.findUnique({
    where: { id: userId },
    select: { scheduledDeletionAt: true, isDeleted: true },
  });

  if (!user) {
    throw new AppError(status.NOT_FOUND, "User not found.");
  }

  if (user.isDeleted) {
    return { message: "User is already deleted." };
  }

  if (!user.scheduledDeletionAt || user.scheduledDeletionAt > new Date()) {
    throw new AppError(
      status.BAD_REQUEST,
      "Deletion date has not been reached yet.",
    );
  }

  // Soft-delete the user
  await prisma.user.update({
    where: { id: userId },
    data: {
      isDeleted: true,
      deletedAt: new Date(),
    },
  });

  // Invalidate all sessions
  await prisma.session.deleteMany({ where: { userId } });

  await auditService.logAction({
    userId,
    action: AUDIT_ACTIONS.ACCOUNT_DELETED,
    entityType: "USER",
    entityId: userId,
  });

  return { message: "Account has been permanently deleted." };
};

export const accountService = {
  requestExport,
  getExportStatus,
  downloadExport,
  requestArchive,
  deactivateAccount,
  reactivateAccount,
  requestDeletion,
  cancelDeletion,
  executeDeletion,
};
